### ISSUE TITLE
nullthrows has either bad condition or bad error message

### ISSUE THREAD

**Issue by hejtmii** [facebook/fbjs#506] opened 2023-04-19 15:34 UTC
Hi, while debugging DraftJS, I found out that the function `nullthrows` checks only for `null`, but its error message says "Got unexpected null or **undefined**"

Also, the way its result is typed seems wrong, because `undefined` passes the condition returning `undefined` where non-nullable `T` should be ...

I would expect it to either check also for `undefined`, or return `T | undefined` and not return `undefined` in the error message ...

https://github.com/facebook/fbjs/blob/d8f0f430a689ee1e5bb070d501155fa29e329019/packages/fbjs/src/utils/nullthrows.js#L15

**Comment by bigfootjon** [comment] 2023-04-19 15:37
> I found out that the function nullthrows checks only for null

That's not correct, the function does a `!= null` check which means that `null` and `undefined` are considered not equal to `null`. If the function instead used `!== null` then you would be correct.

i just double-checked in the JS console in Chrome to be sure:

> null != null
> false
> undefined != null
> false
> 0 != null
> true

I suspect the problem is somewhere else.

**Closed by bigfootjon** 2023-04-19 15:37 UTC
