### ISSUE TITLE
Multiple modules with names that only differ in casing (setImmediate)

### ISSUE THREAD

**Issue by jeremywrowe** [facebook/fbjs#234] opened 2017-04-20 12:27 UTC
I am running into some really odd behavior with fbjs 0.8.12 and webpack 2. I am getting a warning for `setImmediate` referencing the same module name with different casing. It looks like `setimmediate` pollyfill is being wrapped by a `setImmediate` module. Here is the warning that I am seeing (I've removed full paths on the node module references and replaced with ${project-path})
 
```
WARNING in ./~/fbjs/lib/setImmediate.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* ${project-path}/node_modules/fbjs/lib/setImmediate.js
    Used by 1 module(s), i. e.
   ${project-path}/node_modules/draft-js/lib/editOnBeforeInput.js
* ${project-path}/node_modules/fbjs/lib/setimmediate.js
    Used by 2 module(s), i. e.
    ${project-path}/node_modules/fbjs/lib/setImmediate.js
```

As soon as I add content to Editor (in draft-js 0.10.0) I am getting an error:

```
editOnBeforeInput.js?3bad:126 Uncaught TypeError: setImmediate is not a function
    at editOnBeforeInput (eval at ./node_modules/draft-js/lib/editOnBeforeInput.js (bundle.js:1512:1), <anonymous>:126:5)
    at eval (eval at ./node_modules/draft-js/lib/DraftEditor.react.js (bundle.js:1256:1), <anonymous>:144:19)
    at Object.ReactErrorUtils.invokeGuardedCallback (eval at ./node_modules/react-dom/lib/ReactErrorUtils.js (bundle.js:5229:1), <anonymous>:69:16)
    at executeDispatch (eval at ./node_modules/react-dom/lib/EventPluginUtils.js (bundle.js:4949:1), <anonymous>:85:21)
    at Object.executeDispatchesInOrder (eval at ./node_modules/react-dom/lib/EventPluginUtils.js (bundle.js:4949:1), <anonymous>:108:5)
    at executeDispatchesAndRelease (eval at ./node_modules/react-dom/lib/EventPluginHub.js (bundle.js:4933:1), <anonymous>:43:22)
    at executeDispatchesAndReleaseTopLevel (eval at ./node_modules/react-dom/lib/EventPluginHub.js (bundle.js:4933:1), <anonymous>:54:10)
    at Array.forEach (native)
    at forEachAccumulated (eval at ./node_modules/react-dom/lib/forEachAccumulated.js (bundle.js:5645:1), <anonymous>:24:9)
    at Object.processEventQueue (eval at ./node_modules/react-dom/lib/EventPluginHub.js (bundle.js:4933:1), <anonymous>:257:7)
```

It seems to me that the wrapping module name should not match the external library. I'd be glad to open a pull request with a change. Please advise.

**Comment by zpao** [comment] 2017-04-21 00:35
The problem seems to be that you ended up with 2 copies of the same file, just with casing changed:
- `${project-path}/node_modules/fbjs/lib/setImmediate.js`
- `${project-path}/node_modules/fbjs/lib/setimmediate.js`

I'm not sure how you got into that state - `fbjs` doesn't ship like that. The reference we have in our `setImmediate.js` file references a `setimmediate` without any paths (an npm installed dep), so there should be no case where that would be referencing something local.

Do you still get this after clearing out your `node_modules` and reinstalling? If so, could you make a minimal gist or repo that reproduces so we could clone to test this?

**Comment by jeremywrowe** [comment] 2017-04-21 12:01
Thanks for the reply @zpao - I did experience the problem after removing `node_modules` It seems that `setimmediate` is a dependency of both `fbjs` and another module. I will try to reproduce further with a small isolated project.

**Comment by zpao** [comment] 2017-04-21 18:02
Thanks. I'd like to figure out why this is happening and if there is something we can do to avoid it. It might end up being a bug with webpack that we can report.

**Comment by jeremywrowe** [comment] 2017-04-21 23:18
Looks to be a problem with webpack 2.  There are a ton of reports of this in the angular world. http://purpleops.com/articles/webpack-filename-case-warnings/. I am still yet to track down the root cause.

**Comment by jeremywrowe** [comment] 2017-04-21 23:36
I don't see the issue with `draft-js` 0.09.0 and an older version of `fbjs`

**Comment by jeremywrowe** [comment] 2017-05-11 11:16
closing this out because we can't reproduce.

**Comment by confiks** [comment] 2017-05-13 10:25
@jeremywrowe Here is a reproduction case with the latest version of `fbjs`: https://github.com/confiks/setimmediate. See the `build-output.txt` file for the warning.

I encounter this annoying warning message with `draft-js`, which uses a single instance of `setImmediate` somewhere in the code. It seems that when `fbjs/lib/setImmediate` is required, Webpack encounters the `require('setimmediate')` there (without capital), and emits the same file again under the name `fbjs/lib/setimmediate` instead of using the `setimmediate` package out of `node_modules`. So the polyfill isn't actually included in the build (unless of course it is included somewhere else).

**Comment by confiks** [comment] 2017-05-15 15:28
A solution would have been to rename the `fbjs/lib/setImmediate` to something else, but obviously a lot of people depend on this name now.

Changing `require('setimmediate')` to `require('../../setimmediate')` is a solution in the reproduction case, although I don't know if there are other ways to layout the `node_modules` folder so that `../../` cannot be relied upon.

**Comment by zpao** [comment] 2017-05-15 16:46
Thanks for the repro case. I spent a few minutes with it and I hold that this is a webpack bug. Specifically if you get rid of the `resolve` field in `webpack.config.js` then it works fine. Worse: even if you "fix" the warning by renaming the file to be lowercase, then you continue to see the packaging bug that you saw (where the node_module file doesn't get packaged at all). I have a smaller test case that doesn't involve `fbjs` and it's baggage so I'll file a bug.

**Comment by jeremywrowe** [comment] 2017-05-15 16:53
Thanks @zpao!

**Comment by confiks** [comment] 2017-05-15 17:02
@zpao Thanks for the pointer towards `resolve.modules`. This might not even be considered a Webpack bug, but simply an effect of always resolving modules in the current directory (i.e. `resolve.modules = ['.']`) and using a case insensitive filesystem. After using Webpack for so long I almost forgot that the node.js resolving process forces you to explicitly reference the current directory (`./foo.js`).

That `./setImmediate` and `./setimmediate` return the same file when the filsystem is case insensitive is [by design](https://nodejs.org/en/docs/guides/working-with-different-filesystems/).

**Comment by zpao** [comment] 2017-05-15 17:26
Ok, closing out. Thanks again for the repro - it was super helpful!

You might be right that `"."` in there screws it up but I figured it was still worth raising so the webpack folks can decide for sure. I filed https://github.com/webpack/webpack/issues/4876, and used https://github.com/zpao/testcases/tree/webpack-resolve as my simplified test case.

**Closed by zpao** 2017-05-15 17:26 UTC

**Comment by jcardoz** [comment] 2017-12-20 12:34
the problem arises with Angular 4 and webpack when we have the following files in our project

-  multiple modules

- files with both pascal casing `myFile` and dasherized names `another-file`

**Comment by Manish3323** [comment] 2018-01-26 07:28
@jcardoz  i had the same caseSensitive issue upon using webpack 2 along with angular 4 , when i mistakenly created two folders one with camelcase and other with dash/hyphen . Thanks to you .!! on removing one folder and merging  the contents into single directory resolved the issue!!  Thanks again!!

**Comment by paigeflourin** [comment] 2018-11-27 09:37
i have this issue but i am using typescript. how did you resolve this?

**Comment by Manish3323** [comment] 2018-11-27 09:53
please check whether you have something like this in your working directory
**myFile** and **my-file**
https://github.com/facebook/fbjs/issues/234#issuecomment-353051859

**Comment by paigeflourin** [comment] 2018-11-27 10:57
@Manish3323 https://github.com/facebook/draft-js/issues/1943 this is the issue i have posted in draftjs can i just rename the setImmediate to set-immediate?

**Comment by Manish3323** [comment] 2018-11-27 11:11
no no ... after reading your issue,the above wont solve your problem.
i found a solution which says it needs a webpack configuration.
try this 
https://github.com/mozilla-services/react-jsonschema-form/issues/597#issuecomment-307831582

**Comment by paigeflourin** [comment] 2018-11-27 13:37
@Manish3323 about thst, i dont havr a webpack.config.js :( i only have a tsconfig file  that is why i am not sure what to do with this issue

**Comment by pawod** [comment] 2019-07-02 10:48
@paigeflourin did you find a solution?

**Comment by pconnell99** [comment] 2020-05-26 09:28
This is still an issue afaik.  I'm building the component and as well as the setImmediate error (which I've fixed by editing the entry in draft-html require to lowercase), it seems the calendar.scss module is misnamed - and crashing the build.

One way around this is to let it fail after `gulp build` and then run `gulp package-solution --ship` separately, which builds the package for deployment.

Is this ever getting fixed or are we on our own here?

**Comment by Rafaelki** [comment] 2020-09-22 20:07
@paigeflourin , @pconnell99 did you find a way to solve this? 
Modifying files that are going to be overwritten with the next npm install is not an option in my case.
It is very sad we cannot use draft due to an issue with the casing that have not been solve in more than 3 years.

**Comment by pconnell99** [comment] 2020-11-03 10:47
Nothing here, since I got it working for that build I left it.  Bit worrying though eh?

**Comment by mohammadamer** [comment] 2021-11-04 14:34
@pconnell99 
@Rafaelki 
@paigeflourin 

Hi!
I have the same issue with Calendar component built with SPFx framework. Have you fixed the issue?
Modifying files that are going to be overwritten with the next npm install is not an option in my case.

After upgrade my solution to SPFx 1.13.0 I stumbled upon the same issue.
```
./node_modules/fbjs/lib/setImmediate.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
*${project-path}\repos\CalendarWebPart\node_modules\fbjs\lib\setImmediate.js
    Used by 1 module(s), i. e.
    ${project-path}\repos\CalendarWebPart\node_modules\draft-js\lib\editOnBeforeInput.js

* ${project-path}\repos\CalendarWebPart\node_modules\fbjs\lib\setimmediate.js
    Used by 2 module(s), i. e.
    ${project-path}\repos\CalendarWebPart\node_modules\fbjs\lib\setImmediate.js
 @ ./node_modules/fbjs/lib/setImmediate.js
 @ ./node_modules/draft-js/lib/editOnBeforeInput.js
 @ ./node_modules/draft-js/lib/DraftEditorEditHandler.js
 @ ./node_modules/draft-js/lib/DraftEditor.react.js
 @ ./node_modules/draft-js/lib/Draft.js
 @ ./lib/controls/Event/event.js
 @ ./lib/webparts/calendar/components/Calendar.js
 @ ./lib/webparts/calendar/CalendarWebPart.js
```

**Comment by JonathanCardozTakeda** [comment] 2021-11-16 11:54
@mohammadamer - the error message states the same issue - There are multiple modules with names that only differ in casing.

**Comment by matthewjosephtaylor** [comment] 2022-01-23 21:45
This issue still exists in 2022 :)

FYI This fix is to manually edit node_modules/fbjs/lib/setImmediate.js
```
//require("setimmediate");
require("setImmediate");
```
